# import logging
# from typing import List, Optional
# from datetime import datetime

# from celery import shared_task
# from django.utils import timezone

# from mota_apps.agents.models.loan_notification_agent import LoanNotificationAgent
# from mota_apps.agents.tasks.loan_email_tasks import send_agent_task_email
# from mota_apps.users.models import User
# from mota_apps.finance.models import Loan

# logger = logging.getLogger(__name__)

# @shared_task
# def run_loan_notification_task(test_user_emails: Optional[List[str]] = None) -> str:
#     try:
#         logger.info(f"[Loan Notification] Started | Test Emails: {test_user_emails or 'None'}")
#         selected_season = {"year": timezone.now().year, "month": timezone.now().month}
#         season_date = datetime(selected_season["year"], selected_season["month"], 1)

#         # Get loans and group by user
#         loans = Loan.objects.filter(
#             season_date=season_date,
#             status__in=['UNPAID', 'PARTIAL'],
#             member__is_active=True,
#             member__is_deleted=False
#         ).select_related("member").order_by("-created")[:100]
        
#         if not loans:
#             logger.info("[Loan Notification] No unpaid or partially paid loans found.")
#             return "No unpaid or partially paid loans found"

#         # Group loans by user
#         user_loans = {}
#         for loan in loans:
#             user = loan.member
#             if user.email not in user_loans:
#                 user_loans[user.email] = []
#             user_loans[user.email].append({
#                 "member_name": user.get_full_name,
#                 "amount_borrowed": float(loan.amount_borrowed),
#                 "amount_paid": float(loan.amount_paid),
#                 "amount_left_to_pay": float(loan.amount_left_to_pay),
#                 "borrow_date": loan.borrow_date.strftime('%Y-%m-%d'),
#                 "status": loan.status,
#             })
        
#         logger.info(f"[Loan Notification] Found {len(loans)} loans for {len(user_loans)} users")

#         # Determine which users to notify
#         if test_user_emails:
#             user_emails = [email for email in test_user_emails if email in user_loans]
#             logger.info(f"[Loan Notification] Using test emails: {user_emails}")
#         else:
#             user_emails = list(user_loans.keys())
#             logger.info(f"[Loan Notification] Notifying {len(user_emails)} users with unpaid/partially paid loans")

#         if not user_emails:
#             logger.info("[Loan Notification] No users to notify after filtering.")
#             return "No users with unpaid or partially paid loans found"

#         # Run agent to generate message template
#         agent = LoanNotificationAgent(prompt_version="v1")
#         output = agent.run_agent(season_date)
#         logger.debug(f"Agent output: {output}")

#         if not output["message"] or not output["loans"]:
#             logger.info("[Loan Notification] Agent returned no message or loans.")
#             return "No message or loans generated by agent"

#         # Send emails to users with their specific loans
#         notified_users = 0
#         total_loans = 0
#         for email in user_emails:
#             user_specific_loans = user_loans.get(email, [])
#             if user_specific_loans:
#                 logger.info(f"[Loan Notification] Queueing email to {email} with {len(user_specific_loans)} loans")
#                 send_agent_task_email.delay(
#                     user_email=email,
#                     task_type="loan_notification",
#                     status="success",
#                     details={
#                         "message": output["message"],
#                         "loans": user_specific_loans,
#                         "season_date": season_date.strftime('%Y-%m-%d'),
#                     },
#                 )
#                 notified_users += 1
#                 total_loans += len(user_specific_loans)

#         result_message = f"Notified {notified_users} users about {total_loans} loans"
#         logger.info(f"[Loan Notification] Completed | {result_message}")
#         return result_message

#     except Exception as e:
#         logger.error("[Loan Notification] Failed", exc_info=True)
#         raise