# Generated by Django 5.2.4 on 2025-10-18 02:33

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Marks the record as deleted without removing it.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stores additional metadata in JSON format.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('season_date', models.DateField(db_index=True, help_text='Season date (e.g., 2025-01-01 for January 2025).')),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Collected')),
                ('signature', models.TextField(blank=True, help_text='Digital signature data for collection confirmation.', null=True, verbose_name='Signature')),
                ('member', models.ForeignKey(help_text='The member who made the collection.', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'constraints': [models.UniqueConstraint(fields=('member', 'season_date'), name='unique_member_season_collection')],
            },
        ),
    ]
