# Generated by Django 5.2.4 on 2025-10-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrecord',
            name='signature',
            field=models.TextField(blank=True, help_text='Digital signature data for collection confirmation.', null=True, verbose_name='Signature'),
        ),
    ]
