# Generated by Django 5.2.4 on 2025-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_projectrecord_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrecord',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to the uploaded project form (PDF, JPG, PNG).', max_length=255, null=True, verbose_name='Uploaded File'),
        ),
    ]
