# Generated by Django 5.2.4 on 2025-10-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_projectrecord_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrecord',
            name='file_path',
            field=models.FileField(blank=True, help_text='Uploaded project form (PDF, JPG, PNG).', null=True, upload_to='uploads/projects/', verbose_name='Uploaded File'),
        ),
    ]
